version: 0.2

phases:
  install:
    runtime-versions:
    {% if cookiecutter.runtime == "java" %}                    
      java: openjdk8  
    {% else %}
      dotnet: 2.2
    {% endif %}      
    commands:
      # Use Install phase to install packages or any pre-reqs you may need throughout the build (e.g. dev deps, security checks, etc.)
      - echo "[Install phase]"
      #- pip install --upgrade awscli
      - pip install aws-sam-cli
      
  build:
    commands:
      - echo "[Build phase]"
      - sam build
      
  post_build:
    commands:
      # Use Post Build for notifications, git tags and any further customization after build
      - echo "[Post-Build phase]"
      - sam package --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml
      - echo "Packaging completed on `date`"

##################################
# Build Artifacts to be uploaded #
##################################

artifacts:
  files:
    # list of local files relative to this build environment that will be added to the final artifact (zip)
    - packaged.yaml
  
#########################################
# Cache local files for subsequent runs #
#########################################

cache:
  paths:
  # List of path that CodeBuild will upload to S3 Bucket and use in subsequent runs to speed up Builds
  # - '/root/.cache/pip'
